
#ifndef CELL_CODING_STREAM_SPU2_MSG_H
#define CELL_CODING_STREAM_SPU2_MSG_H 1

enum {
	SPU2_MSG_SPU_TO_PPU_DONE 	= 1,
	
	SPU2_MSG_PPU_TO_SPU_EXIT 	= 10,
	SPU2_MSG_PPU_TO_SPU_DO_COPY 	= 11,
	SPU2_MSG_PPU_TO_SPU_DO_SCALE 	= 12,
	SPU2_MSG_PPU_TO_SPU_DO_ADD 	= 13,
	SPU2_MSG_PPU_TO_SPU_DO_TRIAD 	= 14
};

#endif

